spring:
  application:
    name: ReaderAssisstant

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/reader_assistant
    username: ${POSTGRES_USER:guijas1}
    password: ${POSTGRES_PASSWORD:3437}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true