CREATE TABLE reader_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(1000),
    tipo_reader VARCHAR(20) NOT NULL,
    total_paginas INTEGER NOT NULL,
    arquivo_chave VARCHAR(500) NOT NULL,
    nome_arquivo VARCHAR(255),
    tamanho_arquivo_bytes BIGINT,
    data_importacao TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT ck_reader_entity_tipo_reader
        CHECK (tipo_reader IN ('LIVRO', 'MANGA', 'NOVEL')),
    CONSTRAINT ck_reader_entity_total_paginas
        CHECK (total_paginas >= 1),
    CONSTRAINT ck_reader_entity_tamanho_arquivo
        CHECK (tamanho_arquivo_bytes IS NULL OR tamanho_arquivo_bytes >= 0)
);
