CREATE TABLE progresso_livro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,
    pagina_atual INTEGER NOT NULL DEFAULT 0,
    iniciado_em TIMESTAMP WITHOUT TIME ZONE,
    finalizado_em TIMESTAMP WITHOUT TIME ZONE,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT uk_progresso_usuario_livro
        UNIQUE (usuario_id, livro_id),
    CONSTRAINT fk_progresso_livro_livro
        FOREIGN KEY (livro_id) REFERENCES reader_entity (id),
    CONSTRAINT ck_progresso_livro_pagina_atual
        CHECK (pagina_atual >= 0)
);

CREATE INDEX idx_progresso_livro_livro_id
    ON progresso_livro (livro_id);
